### PR TITLE
Version upgrades: Terraform -> v1.0.0, AWS TF Provider -> v3.37.0, AWS TF EKS module -> v15.2.0

### PR DESCRIPTION
**Pull request by awsitcloudpro**
*Issue #, if available:*
Issue #4

*Description of changes:*
Changes necessary to use this repo with Terraform v0.15.0 / v1.0.0:
* Used TF function [tomap()](https://www.terraform.io/docs/language/functions/map.html) instead of map(), which is deprecated and no longer available.
* Used TF function [tolist()](https://www.terraform.io/docs/language/functions/tolist.html) instead of list(), which is deprecated and no longer available. The list() function was used in the older version of the dependency module terraform-aws-modules/eks/aws, so to it was necessary to [upgrade the module version to 15.2.0](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1317), which in turn also necessitated [TF AWS provider version upgrade to 3.37.0](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1340). 
* Updated Deployment Steps in README to use the source directory as the current working directory, as [required by TF v0.15.0+](https://www.terraform.io/docs/cli/commands/init.html#passing-a-different-configuration-directory). Also fixed the pre-requisites bullets.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vara-bonthu** [comment]
@awsitcloudpro Thanks for your contribution.  I will review and test the PR this weekend and merge it accordingly

**Comment by awsitcloudpro** [comment]
@vara-bonthu I had forgotten to update Makefile, did that now.

**Comment by vara-bonthu** [comment]
@awsitcloudpro Could you please resolve the conflicts and submit the PR? Alos, Please ensure your Terraform version update is working end to end by deploying the DEV cluster as per the instructions end to end

**Comment by awsitcloudpro** [comment]
@vara-bonthu I have resolved the conflicts that happened due to the recent main branch commits. I have also re-tested the version upgrade end-to-end, including Agones and Traefik IC deployment. Everything worked well.

**Comment by awsitcloudpro** [comment]
Closing, as the new release incorporates TF version upgrade.

**Pull request closed without merging**
