### PR TITLE
Issue, Feature Request and PR templates added

### PR DESCRIPTION
**Pull request by vara-bonthu**
*Issue #, if available:*

*Description of changes:*
- Issue template added for users to raise Issues in specific format
- Feature Request template 
- PR templates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by askulkarni2 — COMMENTED** [review]
Lets add one more template for Questions.

**Comment by vara-bonthu** [comment]
> Lets add one more template for Questions.

Updated PR with Question template.

**Review by askulkarni2 — APPROVED** [review]
Love it!! Thanks for this.

**Review by kcoleman731 — APPROVED** [review]
Awesome. See formatting issues in CI!

**Pull request merged**
