### PR TITLE
addons: add Tetrate Istio Distribution addon

### PR DESCRIPTION
**Pull request by yskopets**
### What does this PR do?

This PR adds an addon for installing [Tetrate Istio Distribution](https://istio.tetratelabs.io/) into EKS cluster.

### Motivation

Include enterprise-grade Istio distribution into SSP.

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [x] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable) - [ssp-eks-add-ons#22](https://github.com/aws-samples/ssp-eks-add-ons/pull/22)
- [x] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [x] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by askulkarni2** [comment]
@yskopets thank you so much for your PR. At this point we are requesting partners follow this [extensibility guide](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/extensibility.md) to create addons. Looking at your PR it would mean that `modules/kubernetes-addons/istio` would move to a separate repo under your GitHub organization.

**Comment by askulkarni2** [comment]
@yskopets thank you so much for your PR. At this point we are requesting partners follow this [extensibility guide](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/blob/main/docs/extensibility.md) to create addons. Looking at your PR it would mean that `modules/kubernetes-addons/istio` would move to a separate repo under your GitHub organization.

**Comment by yskopets** [comment]
@askulkarni2 I've refactored the PR.

Please take another look.

**Review by vara-bonthu — APPROVED** [review]
@yskopets Thanks for the PR. This looks good to me 👍🏼  
Could you please add an example to this add-on?

**Review by askulkarni2 — COMMENTED** [review]
@yskopets thank you for the updates. PR is looking good. Only change we want to request is to pin the reference to `helm-addon` module to a release tag (latest is 3.5.0) in https://github.com/tetratelabs/terraform-eksblueprints-tetrate-istio-addon/blob/main/main.tf. E.g.

```hcl
source            = "github.com/aws-samples/aws-eks-accelerator-for-terraform//modules/kubernetes-addons/helm-addon?ref=v3.5.0"
```

We saw some issues recently without the version pinning and want to avoid getting into a situation where core framework breaks due to external addons. I will publish an update to the extension guide and example addon soon.

Let me know when you have done this change and tested this and we can approve and merge the PR.

**Comment by yskopets** [comment]
@vara-bonthu Added example. PTAL.

**Comment by yskopets** [comment]
@askulkarni2 I've updated the PR. PTAL.

**Review by vara-bonthu — APPROVED** [review]
HI @yskopets Firstly, thanks and it all looks good now 👍🏼  However there is a confusion around example which i should have been more clearer in my previous comment.

We would like this example(examples/tetrate-istio) to be added to your repo(https://github.com/tetratelabs/terraform-eksblueprints-tetrate-istio-addon) but not in this accelerator repo. It will be easier for you to update this example for any changes.

We will update the extensibility doc as well 

@askulkarni2 Do you have any further comments on this?

**Comment by yskopets** [comment]
@vara-bonthu I've moved the example to my repo. PTAL.

**Review by vara-bonthu — APPROVED** [review]
LGTM 👍🏼  One more approval and then we can merge it

@askulkarni2 @kcoleman731 Please take a look

**Review by askulkarni2 — APPROVED** [review]
@yskopets thanks for the updates. PR looks good to me.

**Pull request merged**
