### PR TITLE
fix: adding depndencies observability example

### PR DESCRIPTION
**Pull request by Zvikan**
### What does this PR do?

- Adding `depends_on` for observability example to correct resources flow creation (VPC -> Cluster -> Addons etc.)

### Motivation
- addressing https://github.com/aws-samples/aws-eks-accelerator-for-terraform/issues/267 issue(s)
- `aws_iam_service_linked_role` should be deleted only after the opensearch is deleted
- fixing failures around context deadlines and time outs for the example

### More

- [X] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [ ] Yes, I have added a new example under [examples](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/examples) to support my PR
- [ ] Yes, I have created another PR for add-ons under [add-ons](https://github.com/aws-samples/ssp-eks-add-ons) repo (if applicable)
- [ ] Yes, I have updated the [docs](https://github.com/aws-samples/aws-eks-accelerator-for-terraform/tree/main/docs) for this feature
- [X] Yes, I ran `pre-commit run -a` with this PR

**Note**: Not all the PRs required examples and docs except a new pattern or add-on added.

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by kcoleman731 — APPROVED** [review]
LGTM

**Review by naris-silpakit — APPROVED** [review]
LGTM!

**Review by askulkarni2 — CHANGES_REQUESTED** [review]
Looks good just one tiny fix.

**Review by vara-bonthu — APPROVED** [review]
LGTM

**Review by askulkarni2 — APPROVED** [review]

**Pull request merged**
